{% set name = "plotms" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/qcxms/{{ name }}/archive/refs/tags/v.{{ version }}.tar.gz
    sha256: 1fe31f236cb6aa1796b0c9e3fcb1df81a135116e9eb7beb0e56208f30e7561db

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
  host:
    - mctc-lib >=0.3.0

test:
  commands:
    - test -f $PREFIX/bin/{{ name }}

about:
  home: https://github.com/qcxms/PlotMS
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Plot Mass Spectra (PlotMS) plotting program for the QCxMS program
  doc_url: https://xtb-docs.readthedocs.io/en/latest/qcxms_doc/qcxms_plot.html

extra:
  recipe-maintainers:
    - hechth
